name: Tip Toe Imaging
favicon: null
layout_spectrum: 0
typography_spectrum: 0.50782
title: Tip Toe Imaging - Visual Architecture
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#656668'
    - '#e92725'
    - '#8cbf3e'
    - '#f68920'
  brandStrength: 0.5
  lightness: 0.4375
  saturation: 0.9375
  rhythmicContrast: 1
purpose: []
