name: Tip Toe Imaging
favicon: null
layout_spectrum: 0.50501
typography_spectrum: 0.98462
title: Tip Toe Imaging - Visual Architecture
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.625
  lightness: 0.5625
  saturation: 0.4375
  rhythmicContrast: 0.75
purpose: []
