name: Tip Toe Imaging
favicon: null
layout_spectrum: 0
typography_spectrum: 0.50782
title: Tip Toe Imaging - Visual Architecture
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#656668'
    - '#e82725'
    - '#f6891f'
    - '#8cbf3e'
    - '#000000'
  brandStrength: 0.25
  lightness: 0.3125
  saturation: 0.25
  rhythmicContrast: 1
purpose: []
